server {
    listen 80;
    listen [::]:80;
    server_name slavicfall.ru;
    root /var/www/ffone/current;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
    location ~ /\. {
        deny all;
    }
    location ~* \.(?:png|gif|svg|otf|ttf|woff2?|css|js)$ {
        expires 1h;
        try_files $uri =404;
    }
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
}
